# Generated by Django 6.0.5 on 2026-06-04 20:22

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("expenses", "Category")
    default_categories = [
        "Groceries 🛒",
        "Żabka🐸",
        "Food Delivery🛵🍕",
        "Dumb Buys 💰🚫",
        "Subscritions🌐",
        "Rent🏠",
    ]
    for name in default_categories:
        Category.objects.create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_alter_category_name_alter_expense_date"),
    ]
    operations = [
        migrations.RunPython(create_default_categories),
    ]
