# Generated by Django 6.0.5 on 2026-06-05 17:29
from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("expenses", "Category")
    default_categories = [
        "🛸Travel",
        "🚌🚕Transport",
        "🍔Eating out",
        "👕Clothing",
        "💊Health and beauty",
    ]
    for name in default_categories:
        Category.objects.create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_expense_user"),
    ]
    operations = [
        migrations.RunPython(create_default_categories),
    ]
