# Generated by Django 6.0.5 on 2026-06-14 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_reqularpayments_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReqularPayments',
            new_name='RegularPayments',
        ),
    ]
