# Generated by Django 6.0.5 on 2026-06-24 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_rename_reqularpayments_regularpayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpayments',
            name='payment_day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
