# Generated by Django 6.0.5 on 2026-06-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_userprofile_notification_status_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN zł'), ('UAH', 'UAH ₴'), ('EUR', 'EUR €'), ('USD', 'USD $')], default='PLN', max_length=3),
        ),
    ]
