# Generated by Django 6.0.5 on 2026-07-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='day_limit',
            new_name='saving_goal',
        ),
    ]
