# Generated by Django 6.0.5 on 2026-07-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_rename_day_limit_userprofile_saving_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='saving_goal',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='savings_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
